version: "3.9"

services:
  backend:
    build: .
    ports:
      - "4000:8080"

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"